### ISSUE TITLE
No such interface “org.freedesktop.portal.Camera” on object at path /org/freedesktop/portal/desktop

### ISSUE THREAD

**Issue by WhyNotHugo** [flatpak/xdg-desktop-portal#1040]
I'm testing the camera portal with [this xdg-camera.py snippet](https://gitlab.gnome.org/-/snippets/762), but it's failing with error:

```
> python xdp-camera.py
request token: u1, path: /org/freedesktop/portal/desktop/request/1_45/u1
Traceback (most recent call last):
  File "/home/hugo/src/gitlab.gnome.org/snippets/762/xdp-camera.py", line 76, in <module>
    camera_call(portal.AccessCamera, on_access_camera_response)
  File "/home/hugo/src/gitlab.gnome.org/snippets/762/xdp-camera.py", line 48, in camera_call
    return method(*(args + (options, )),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Camera” on object at path /org/freedesktop/portal/desktop
```

Inspecting with `d-feet` reveals that indeed, this interface is not exposed by the portal:

![image](https://github.com/flatpak/xdg-desktop-portal/assets/730811/8a069bda-5b2b-47ed-ba96-f8d7a5cdbbd0)

The portal logs don't reveal anything relevant (e.g.: no mention of `Camera` at all):

```
XDP: load portals from /usr/share/xdg-desktop-portal/portals
XDP: loading /usr/share/xdg-desktop-portal/portals/gtk.portal
XDP: portal implementation for gnome
XDP: portal implementation supports org.freedesktop.impl.portal.FileChooser
XDP: portal implementation supports org.freedesktop.impl.portal.AppChooser
XDP: portal implementation supports org.freedesktop.impl.portal.Print
XDP: portal implementation supports org.freedesktop.impl.portal.Screenshot
XDP: portal implementation supports org.freedesktop.impl.portal.Notification
XDP: portal implementation supports org.freedesktop.impl.portal.Inhibit
XDP: portal implementation supports org.freedesktop.impl.portal.Access
XDP: portal implementation supports org.freedesktop.impl.portal.Account
XDP: portal implementation supports org.freedesktop.impl.portal.Email
XDP: portal implementation supports org.freedesktop.impl.portal.DynamicLauncher
XDP: portal implementation supports org.freedesktop.impl.portal.ScreenCast
XDP: portal implementation supports org.freedesktop.impl.portal.RemoteDesktop
XDP: portal implementation supports org.freedesktop.impl.portal.Lockdown
XDP: portal implementation supports org.freedesktop.impl.portal.Background
XDP: portal implementation supports org.freedesktop.impl.portal.Settings
XDP: portal implementation supports org.freedesktop.impl.portal.Wallpaper
XDP: loading /usr/share/xdg-desktop-portal/portals/wlr.portal
XDP: portal implementation for wlroots, sway, Wayfire, river, phosh, Hyprland
XDP: portal implementation supports org.freedesktop.impl.portal.Screenshot
XDP: portal implementation supports org.freedesktop.impl.portal.ScreenCast
XDP: loading /usr/share/xdg-desktop-portal/portals/darkman.portal
XDP: portal implementation for sway
XDP: portal implementation supports org.freedesktop.impl.portal.Settings
XDP: Creating dummy proxy for org.freedesktop.impl.portal.Lockdown on org.freedesktop.impl.portal.desktop.gtk
XDP: Failed to create dummy fallback proxy on org.freedesktop.impl.portal.desktop.gtk for org.freedesktop.impl.portal.Lockdown: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
XDP: providing portal org.freedesktop.portal.MemoryMonitor
XDP: providing portal org.freedesktop.portal.PowerProfileMonitor
XDP: providing portal org.freedesktop.portal.NetworkMonitor
XDP: providing portal org.freedesktop.portal.ProxyResolver
XDP: providing portal org.freedesktop.portal.Trash
XDP: providing portal org.freedesktop.portal.GameMode

(/usr/libexec/xdg-desktop-portal:17281): xdg-desktop-portal-WARNING **: 02:06:26.444: Failed to load RealtimeKit property: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(/usr/libexec/xdg-desktop-portal:17281): xdg-desktop-portal-WARNING **: 02:06:26.444: Failed to load RealtimeKit property: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files

(/usr/libexec/xdg-desktop-portal:17281): xdg-desktop-portal-WARNING **: 02:06:26.444: Failed to load RealtimeKit property: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.RealtimeKit1 was not provided by any .service files
XDP: providing portal org.freedesktop.portal.Realtime
XDP: Using darkman.portal for org.freedesktop.impl.portal.Settings
XDP: Using gtk.portal for org.freedesktop.impl.portal.Settings

(/usr/libexec/xdg-desktop-portal:17281): xdg-desktop-portal-WARNING **: 02:06:26.450: Failed to create settings proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
XDP: providing portal org.freedesktop.portal.Settings
XDP: Creating dummy proxy for org.freedesktop.impl.portal.FileChooser on org.freedesktop.impl.portal.desktop.gtk
XDP: Failed to create dummy fallback proxy on org.freedesktop.impl.portal.desktop.gtk for org.freedesktop.impl.portal.FileChooser: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
XDP: Creating dummy proxy for org.freedesktop.impl.portal.AppChooser on org.freedesktop.impl.portal.desktop.gtk
XDP: Failed to create dummy fallback proxy on org.freedesktop.impl.portal.desktop.gtk for org.freedesktop.impl.portal.AppChooser: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
XDP: Creating dummy proxy for org.freedesktop.impl.portal.Print on org.freedesktop.impl.portal.desktop.gtk
XDP: Failed to create dummy fallback proxy on org.freedesktop.impl.portal.desktop.gtk for org.freedesktop.impl.portal.Print: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
XDP: Creating dummy proxy for org.freedesktop.impl.portal.Notification on org.freedesktop.impl.portal.desktop.gtk
XDP: Failed to create dummy fallback proxy on org.freedesktop.impl.portal.desktop.gtk for org.freedesktop.impl.portal.Notification: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
XDP: Creating dummy proxy for org.freedesktop.impl.portal.Inhibit on org.freedesktop.impl.portal.desktop.gtk
XDP: Failed to create dummy fallback proxy on org.freedesktop.impl.portal.desktop.gtk for org.freedesktop.impl.portal.Inhibit: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
XDP: Creating dummy proxy for org.freedesktop.impl.portal.Access on org.freedesktop.impl.portal.desktop.gtk
XDP: Failed to create dummy fallback proxy on org.freedesktop.impl.portal.desktop.gtk for org.freedesktop.impl.portal.Access: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
XDP: Creating dummy proxy for org.freedesktop.impl.portal.Screenshot on org.freedesktop.impl.portal.desktop.wlr
XDP: Dummy proxy created
XDP: Using wlr.portal for org.freedesktop.impl.portal.Screenshot in sway
XDP: Creating dummy proxy for org.freedesktop.impl.portal.Background on org.freedesktop.impl.portal.desktop.gtk
XDP: Failed to create dummy fallback proxy on org.freedesktop.impl.portal.desktop.gtk for org.freedesktop.impl.portal.Background: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
XDP: Creating dummy proxy for org.freedesktop.impl.portal.Wallpaper on org.freedesktop.impl.portal.desktop.gtk
XDP: Failed to create dummy fallback proxy on org.freedesktop.impl.portal.desktop.gtk for org.freedesktop.impl.portal.Wallpaper: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
XDP: Creating dummy proxy for org.freedesktop.impl.portal.Account on org.freedesktop.impl.portal.desktop.gtk
XDP: Failed to create dummy fallback proxy on org.freedesktop.impl.portal.desktop.gtk for org.freedesktop.impl.portal.Account: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
XDP: Creating dummy proxy for org.freedesktop.impl.portal.Email on org.freedesktop.impl.portal.desktop.gtk
XDP: Failed to create dummy fallback proxy on org.freedesktop.impl.portal.desktop.gtk for org.freedesktop.impl.portal.Email: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
XDP: Creating dummy proxy for org.freedesktop.impl.portal.DynamicLauncher on org.freedesktop.impl.portal.desktop.gtk
XDP: Failed to create dummy fallback proxy on org.freedesktop.impl.portal.desktop.gtk for org.freedesktop.impl.portal.DynamicLauncher: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
XDP: Creating dummy proxy for org.freedesktop.impl.portal.ScreenCast on org.freedesktop.impl.portal.desktop.wlr
XDP: Dummy proxy created
XDP: Using wlr.portal for org.freedesktop.impl.portal.ScreenCast in sway
XDP: providing portal org.freedesktop.portal.ScreenCast
XDP: Creating dummy proxy for org.freedesktop.impl.portal.RemoteDesktop on org.freedesktop.impl.portal.desktop.gtk
XDP: Failed to create dummy fallback proxy on org.freedesktop.impl.portal.desktop.gtk for org.freedesktop.impl.portal.RemoteDesktop: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
XDP: org.freedesktop.portal.Desktop acquired
```

I'm using `xdg-desktop-portal-1.16.0-r2` from Alpine Edge repositories on x86_64.

**Comment by smcv** [comment]
> ```
> XDP: Failed to create dummy fallback proxy on org.freedesktop.impl.portal.desktop.gtk for org.freedesktop.impl.portal.Inhibit: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Process org.freedesktop.impl.portal.desktop.gtk exited with status 1
> ```

Your xdg-desktop-portal-gtk installation appears to be broken. Please check your system log (systemd journal or syslog) or consult your distribution's support channels.

The Camera portal is one of several that require the Access backend, and gtk.portal appears to be the only implementation of Access that you have; so if that's broken, then Camera, Location, Screenshot, Background and Wallpaper are also not going to work.

**Comment by WhyNotHugo** [comment]
`Screenshot` requires the access portal but `Screencast` does not.

Is this because Screencast is subject to the compositor-specific prompt anyway?

**Comment by WhyNotHugo** [comment]
`xdg-desktop-portal-gtk` only worked the first time. Successive attempts no longer work. There's no error output now, and `xdg-desktop-portal` merely prints:

    XDP: Camera: sending response 0

Given the error output, I'm fairly certain that the issue is now on the `xdp-camera.py` side, and the screencasting is now being allowed implicitly and with no access prompt.

To understand what going on a bit better, I tried writing my own access portal (this will also be useful in future). It is effectively being used by `xdg-desktop-portal`:

```
XDP: Creating dummy proxy for org.freedesktop.impl.portal.Access on org.freedesktop.impl.portal.desktop.way-access
XDP: Dummy proxy created
XDP: Using way-access.portal for org.freedesktop.impl.portal.Access in sway
```

But it's not being called at all.

As a side note, [the documentation does not describe what `AccessDialog`](https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-impl-portal-Access.AccessDialog) should return. Any hints on what the return value should be?
