### ISSUE TITLE
Clicking http:// URI in flatpak app does not work if URI handler is also a flatpak app

### ISSUE THREAD

**Issue by mcatanzaro** [flatpak/xdg-desktop-portal#173]
Clicking an http:// URI in flatpak app does not work if URI handler is also a flatpak app.

I noticed this bug yesterday in two different Flatpak applications: org.aperezdc.Riot and org.gnome.Fractal. Clicking an http:// URI in either app opens epiphany, but the URI does not make it through the portal, so it just opens an empty tab instead of the desired URI. My default browser is the flatpak org.gnome.Epiphany. It works fine if the default browser is not itself a Flatpak.

xdg-desktop-portal-0.9.1.fc27 prints the following criticals when clicking on the URI:

```
Mar 22 15:41:30 victory-road xdg-desktop-por[3870]: Error updating permission store: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for x-scheme-handler/http
Mar 22 15:41:30 victory-road xdg-desktop-por[3870]: g_path_get_basename: assertion 'file_name != NULL' failed
Mar 22 15:41:30 victory-road xdg-desktop-por[3870]: g_path_get_dirname: assertion 'file_name != NULL' failed
Mar 22 15:41:30 victory-road xdg-desktop-por[3870]: expand_macro_uri: assertion 'uri != NULL' failed
Mar 22 15:41:30 victory-road xdg-desktop-por[3870]: g_file_new_for_uri: assertion 'uri != NULL' failed
Mar 22 15:41:30 victory-road xdg-desktop-por[3870]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 22 15:41:30 victory-road xdg-desktop-por[3870]: g_variant_new_string: assertion 'string != NULL' failed
```

@matthiasclasen reports seeing a different warning when testing this case:

```
WARNING **: 16:36:59.419: Error registering http://www.gnome.org for org.gnome.Epiphany: Failed to open http://www.gnome.org
```

The difference is that Matthias is using rawhide and must have xdg-desktop-portal 0.10, whereas I have 0.9 on Fedora 27. The warning Matthias is seeing was added by @mariospr in #134.

I tried to make myself useful and debug this a bit further, but wound up giving up due to a separate bug in GIO. After building my own version of xdg-desktop-portal locally and running it from the source directory with `./xdg-desktop-portal --verbose --replace`, Fractal now crashes when clicking on the URI, with the attached backtrace:

```
#0  0x000055ece18176a1 in free (ptr=0x7ff91df2e3e0 <g_idle_dispatch>)
    at /checkout/src/liballoc_jemalloc/../jemalloc/include/jemalloc/internal/arena.h:809
#1  0x00007ff91df371ea in g_free (mem=<optimized out>) at gmem.c:194
#2  0x00007ff91e54b100 in open_call_done (source=0x7ff9000c0200 [GXdpOpenURIProxy], result=0x7ff90e0c4c30, user_data=0x7ff90e122450) at gopenuriportal.c:222
        openuri = 0x7ff9000c0200
        connection = 0x7ff915d10020 [GDBusConnection]
        task = 0x7ff90e122450
        error = 0x7ff9000ccf20
        open_file = <optimized out>
        res = <optimized out>
        path = 0x7ff91df2e3e0 <g_idle_dispatch> "H\205\366t\vH\211\327\377\346f\017\037D"
        handle = <optimized out>
        signal_id = <optimized out>
#3  0x00007ff91e4d9b73 in g_task_return_now (task=0x7ff90e0c4c30 [GTask]) at gtask.c:1148
#4  0x00007ff91e4da636 in g_task_return (task=0x7ff90e0c4c30 [GTask], type=<optimized out>)
    at gtask.c:1206
        source = 0x7ff90e0bfa00
#5  0x00007ff91e518dd9 in reply_cb (connection=<optimized out>, res=<optimized out>, user_data=0x7ff90e0c4c30) at gdbusproxy.c:2586
        task = 0x7ff90e0c4c30 [GTask]
        value = <optimized out>
        error = 0x7ff9000ccf20
        fd_list = 0x7ff90e0bfa00
#6  0x00007ff91e4d9b73 in g_task_return_now (task=0x7ff90e0c4d00 [GTask]) at gtask.c:1148
#7  0x00007ff91e4da636 in g_task_return (task=0x7ff90e0c4d00 [GTask], type=<optimized out>)
    at gtask.c:1206
        source = 0x7ff90e0bfa00
#8  0x00007ff91e50d939 in g_dbus_connection_call_done (source=<optimized out>, result=0x7ff90e0a1930, user_data=0x7ff90e0c4d00) at gdbusconnection.c:5722
        connection = <optimized out>
        task = 0x7ff90e0c4d00 [GTask]
        state = 0x7ff9127016c0
        error = 0x7ff9000ccf20
        reply = 0x7ff90e1291e0 [GDBusMessage]
        value = <optimized out>
#9  0x00007ff91e4d9b73 in g_task_return_now (task=0x7ff90e0a1930 [GTask]) at gtask.c:1148
#10 0x00007ff91e4d9ba9 in complete_in_idle_cb (task=0x7ff90e0a1930) at gtask.c:1162
#11 0x00007ff91df3196a in g_main_context_dispatch (context=0x7ff915c38480) at gmain.c:3177
        dispatch = 0x7ff91df2e3e0 <g_idle_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x7ff90e0a1930
        callback = 0x7ff91e4d9ba0 <complete_in_idle_cb>
        cb_funcs = <optimized out>
        cb_data = 0x7ff90d46f580
        need_destroy = <optimized out>
        source = 0x7ff90e0bfa00
        current = 0x7ff915c17860
        i = 0
#12 0x00007ff91df3196a in g_main_context_dispatch (context=context@entry=0x7ff915c38480) at gmain.c:3830
#13 0x00007ff91df31d28 in g_main_context_iterate (context=context@entry=0x7ff915c38480, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3903
        max_priority = 2147483647
        timeout = 3
        some_ready = 1
        nfds = 4
        allocated_nfds = 4
        fds = <optimized out>
#14 0x00007ff91df31ddc in g_main_context_iteration (context=context@entry=0x7ff915c38480, may_block=may_block@entry=1) at gmain.c:3964
        retval = <optimized out>
#15 0x00007ff91e4ef80d in g_application_run (application=0x7ff915d632b0 [GtkApplication], argc=0, argv=0x7ff915d7ebe0) at gapplication.c:2482
        arguments = 0x7ff915d97920
        status = 0
        context = 0x7ff915c38480
        acquired_context = <optimized out>
        __func__ = "g_application_run"
#16 0x000055ece1565dbc in _$LT$O$u20$as$u20$gio..application..ApplicationExtManual$GT$::run::h7ee0fe6fa9cdbd75 ()
#17 0x000055ece15509ac in fractal_gtk::app::App::new::h54c8ac5309fd4282 ()
#18 0x000055ece156b5bf in fractal_gtk::main::h373d8a75129d3f4f ()
#19 0x000055ece15629d3 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::haad30ff5e573d1e8 ()
#20 0x000055ece17f2a68 in std::panicking::try::do_call::h7d33aea9be52481f ()
    at /checkout/src/libstd/rt.rs:59
#21 0x000055ece17f2a68 in std::panicking::try::do_call::h7d33aea9be52481f ()
    at /checkout/src/libstd/panicking.rs:480
#22 0x000055ece181684f in __rust_maybe_catch_panic () at /checkout/src/libpanic_unwind/lib.rs:101
#23 0x000055ece17f8e6a in std::rt::lang_start_internal::h16c0c37ef62d8e5a ()
    at /checkout/src/libstd/panicking.rs:459
#24 0x000055ece17f8e6a in std::rt::lang_start_internal::h16c0c37ef62d8e5a ()
    at /checkout/src/libstd/panic.rs:365
#25 0x000055ece17f8e6a in std::rt::lang_start_internal::h16c0c37ef62d8e5a ()
    at /checkout/src/libstd/rt.rs:58
#26 0x000055ece156b754 in main ()
```

I'm pretty sure that crash could be fixed by initializing path to NULL in open_call_done() in gopenuriportal.c, since the current code is freeing uninitialized memory in the error path, but this is difficult to test, so I haven't tried. That problem would need to be fixed in GIO to facilitate further debugging of xdg-desktop-portal.

**Comment by matthiasclasen** [comment]
I've pushed the glib fix now

**Comment by matthiasclasen** [comment]
I couldn't conclusively test this patch since running xdg-desktop-portal in a flatpak sandbox is not quite working, but it looks right to me.

**Comment by mcatanzaro** [comment]
I'll do a Fedora scratch build to test the patch.

**Comment by mcatanzaro** [comment]
Tested https://koji.fedoraproject.org/koji/taskinfo?taskID=25969089. Confirmed fixed, thanks!

**Comment by mcatanzaro** [comment]
Although there are still a couple warnings to be fixed:

```
$ /usr/libexec/xdg-desktop-portal -r

** (/usr/libexec/xdg-desktop-portal:3829): WARNING **: Error updating permission store: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for x-scheme-handler/https

** (/usr/libexec/xdg-desktop-portal:3829): WARNING **: Error updating permission store: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for x-scheme-handler/https
```

**Comment by matthiasclasen** [comment]
hmm, did you get an app chooser dialog when those warnings were happening ?

**Comment by mcatanzaro** [comment]
No, there is no app chooser dialog. I can reproduce the warning at will by clicking any link in fractal while running the new xdg-desktop-portal. Note that I'm running version 0.9 with that patch backported, not version 0.10.

**Comment by matthiasclasen** [comment]
oh, misleading warning. This should just be removed

**Comment by mariospr** [comment]
> oh, misleading warning. This should just be removed

PR ready for those pesky warnings: https://github.com/flatpak/xdg-desktop-portal/pull/180

(and reopening this bug temporarily)
