### ISSUE TITLE
Illegal instruction in permission store

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal#386]
Some of the tests are hitting this in the CI. I can't reproduce this locally.

```
[New Thread 0x7ffff08f8700 (LWP 19732)]
[Thread 0x7ffff10f9700 (LWP 19731) exited]
[Thread 0x7ffff18fa700 (LWP 19730) exited]
[Thread 0x7ffff7fd98c0 (LWP 19725) exited]
[Inferior 1 (process 19725) exited with code 01]
No stack.
Starting program: /home/runner/work/xdg-desktop-portal/xdg-desktop-portal/xdg-permission-store 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff18fa700 (LWP 19797)]
[New Thread 0x7ffff10f9700 (LWP 19798)]
[New Thread 0x7ffff08f8700 (LWP 19799)]
[Thread 0x7ffff08f8700 (LWP 19799) exited]
[Thread 0x7ffff10f9700 (LWP 19798) exited]
[Thread 0x7ffff7fd98c0 (LWP 19793) exited]
[Inferior 1 (process 19793) exited with code 01]
No stack.
Starting program: /home/runner/work/xdg-desktop-portal/xdg-desktop-portal/xdg-permission-store 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff18fa700 (LWP 19842)]
[New Thread 0x7ffff10f9700 (LWP 19843)]
[New Thread 0x7ffff08f8700 (LWP 19844)]

Thread 1 "xdg-permission-" received signal SIGILL, Illegal instruction.
0x000055555557c228 in file_builder_add_hash ()
#0  0x000055555557c228 in file_builder_add_hash ()
#1  0x000055555557be5d in file_builder_add_hash ()
#2  0x000055555557caee in gvdb_table_get_content ()
#3  0x0000555555575852 in permission_db_update ()
#4  0x0000555555570178 in start_writeout ()
#5  0x0000555555570c23 in handle_set_permission ()
#6  0x00007ffff4626dae in ffi_call_unix64 ()
    at /usr/lib/x86_64-linux-gnu/libffi.so.6
#7  0x00007ffff462671f in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#8  0x00007ffff65e5b31 in g_cclosure_marshal_generic ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff65e533d in g_closure_invoke ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff65f8b7e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff66007a0 in g_signal_emitv ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00005555555807e8 in _xdg_permission_store_skeleton_handle_method_call ()
#13 0x00007ffff69425d7 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#14 0x00007ffff6929ae9 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#15 0x00007ffff6301875 in g_main_context_dispatch ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff6301c40 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff6301f52 in g_main_loop_run ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00005555555652fa in main ()
```

**Comment by matthiasclasen** [comment]
I found a fix in glib: https://gitlab.gnome.org/GNOME/glib/commit/e5ed410c8c0fe823883b65b293fb2d9c9d12673a
