### ISSUE TITLE
Criticals, cannot open images after eog desktop file rename

### ISSUE THREAD

**Issue by mcatanzaro** [flatpak/xdg-desktop-portal#480]
[Original Epiphany bug](https://gitlab.gnome.org/GNOME/epiphany/-/issues/1156):

> Download this screenshot using Tech Preview, then open the Downloads popover and click the folder icon.
>
> Expected behavior: OpenURI portal opens the screenshot
>
> Actual behavior: nothing happens
>
> I wonder if the portal has changed somehow.

I have: xdg-desktop-portal-1.7.2-1.fc32 and xdg-desktop-portal-gtk-1.7.1-1.fc32.

I see a bunch of criticals in my journal:

```
Apr 20 10:11:26 chargestone-cave xdg-desktop-por[3449]: g_desktop_app_info_get_string: assertion 'G_IS_DESKTOP_APP_INFO (info)' failed
Apr 20 10:11:26 chargestone-cave xdg-desktop-por[3449]: g_app_info_launch_uris: assertion 'G_IS_APP_INFO (appinfo)' failed
Apr 20 10:11:27 chargestone-cave xdg-desktop-por[3449]: g_desktop_app_info_get_string: assertion 'G_IS_DESKTOP_APP_INFO (info)' failed
Apr 20 10:11:27 chargestone-cave xdg-desktop-por[3449]: g_app_info_launch_uris: assertion 'G_IS_APP_INFO (appinfo)' failed
Apr 20 10:11:27 chargestone-cave xdg-desktop-por[3449]: g_desktop_app_info_get_string: assertion 'G_IS_DESKTOP_APP_INFO (info)' failed
Apr 20 10:11:27 chargestone-cave xdg-desktop-por[3449]: g_app_info_launch_uris: assertion 'G_IS_APP_INFO (appinfo)' failed
```

Backtrace:

```
(gdb) bt full
#0  0x00007f9684719002 in g_logv () at /lib64/libglib-2.0.so.0
#1  0x00007f9684719273 in g_log () at /lib64/libglib-2.0.so.0
#2  0x00007f9684913a42 in g_desktop_app_info_get_string () at /lib64/libgio-2.0.so.0
#3  0x000055a8252fe64a in is_sandboxed (info=0x0) at src/open-uri.c:239
        flatpak = 0x0
        desktop_id = 0x7f96680158c0 "eog.desktop"
        info = 0x0
        context = 0x7f96680092d0
        ruri = 0x0
        uris = {data=0x7f9668014710, next=0x7f96667fbcc8, prev=0x7f96667fbcb4}
#4  launch_application_with_uri
    (choice_id=0x7f965c0226a0 "eog", uri=0x7f965c0059a0 "file:///home/mcatanzaro/Downloads/Screenshot%20from%202020-04-13%2014-14-54.png", parent_window=0x7f965c004ca0 "", writable=0) at src/open-uri.c:239
        desktop_id = 0x7f96680158c0 "eog.desktop"
        info = 0x0
        context = 0x7f96680092d0
        ruri = 0x0
        uris = {data=0x7f9668014710, next=0x7f96667fbcc8, prev=0x7f96667fbcb4}
#5  0x000055a8252ffaa9 in handle_open_in_thread_func
    (task=<optimized out>, source_object=<optimized out>, task_data=0x7f9668003e90, cancellable=<optimized out>)
    at src/open-uri.c:697
        result = <optimized out>
        app = 0x7f965c0226a0 "eog"
        request = 0x7f9668003e90
        parent_window = 0x7f965c004ca0 ""
        app_id = 0x7f965c001c80 "org.gnome.Epiphany.Devel"
        uri = 0x7f965c0059a0 "file:///home/mcatanzaro/Downloads/Screenshot%20from%202020-04-13%2014-14-54.png"
        impl_request = 0x0
        default_app = 0x7f965c005750 "org.gnome.eog"
        choices = 0x7f965c01fc60
        n_choices = 1
        scheme = 0x7f9668014710 "file"
        content_type = 0x7f965c004e30 "image/png"
        latest_id = 0x7f965c0226a0 "eog"
        basename = 0x7f96680151f0 "Screenshot from 2020-04-13 14-14-54.png"
        latest_count = 14
        latest_threshold = 3
        ask_for_content_type = 0
        opts_builder = 
              {u = {s = {partial_magic = 0, type = 0x8, y = {140283941469456, 8, 140283765348336, 140284444128746, 140727268014638, 500000, 140283941469552, 39, 140284033773248, 140284443952852, 1, 0, 7949933800, 15000}}, x = {0, 8, 140283941469456, 8, 140283765348336, 140284444128746, 140727268014638, 500000, 140283941469552, 39, 140284033773248, 140284443952852, 1, 0, 7949933800, 15000}}}
        skip_app_chooser = 1
        fd = <optimized out>
        writable = 0
        ask = 0
        open_dir = <optimized out>
        can_skip = <optimized out>
        reason = <optimized out>
        request_auto_unlock571 = 0x7f9668003ed0
#6  0x00007f96848fab72 in g_task_thread_pool_thread () at /lib64/libgio-2.0.so.0
#7  0x00007f968473c0f4 in g_thread_pool_thread_proxy () at /lib64/libglib-2.0.so.0
#8  0x00007f968473b7f2 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#9  0x00007f9684689432 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140283941472000, -2603008785386648589, 140727267153598, 140727267153599, 140727267153744, 140283941472000, 2651650078201007091, 2651856690633034739}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#10 0x00007f96845b79d3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Problem is that the Eye of GNOME desktop file was renamed from eog.desktop to org.gnome.eog.desktop. (Cue Matthias: "don't rename things!") Now xdg-desktop-portal has no way to manually select a new application to use once a particular app was used three times to open the file, it just fails. Another way to reproduce this would likely be to simply uninstall the application previously used to open the content type.

Problem two is that launch_application_with_uri() is not prepared for g_desktop_app_info_new() to return NULL.

Suggestion: launch_application_with_uri() should return FALSE if g_desktop_app_info_new() returns NULL, instead of criticals. Then handle_open_in_thread_func() should go ahead and call xdg_impl_app_chooser_call_choose_application() when launch_application_with_uri() returns FALSE, since the easy fallback is to just not skip running the app chooser and let the user try to pick something else.

**Comment by mcatanzaro** [comment]
Fixed in #473
