### ISSUE TITLE
Installed tests still failing on 1.7.2

### ISSUE THREAD

**Issue by jtojnar** [flatpak/xdg-desktop-portal#502]
While https://github.com/flatpak/xdg-desktop-portal/pull/428 fixed many of the issues with installed tests https://github.com/flatpak/xdg-desktop-portal/pull/447 introduced new ones:

<details>
<summary>Log</summary>

```
machine # [   14.075027] gnome-desktop-testing-runner[659]: PASS: xdg-desktop-portal/testdb.test
machine # [   14.403033] gnome-desktop-testing-runner[659]: FAIL: xdg-desktop-portal/test-document-fuse.sh.test (Child process exited with code 127)
machine # [   14.662036] gnome-desktop-testing-runner[659]: PASS: xdg-desktop-portal/test-permission-store.test
machine # [   14.690176] gnome-desktop-testing-runner[659]: SUMMARY: total=5; passed=3; skipped=0; failed=2; user=0.1s; system=0.2s; maxrss=7392
machine: output: Running test: xdg-desktop-portal/test-doc-portal.test
# random seed: R02S248c8daef93c117e9012c955ee64df33
# Successfully set up test FUSE fs on /tmp/xdp-test.BRQBM0
outdir: /tmp/xdp-test-5Z19L0
# GLib-DEBUG: Launching with posix_spawn
dbus-daemon[712]: [session uid=0 pid=712] Activating service name='org.freedesktop.portal.Documents' requested by ':1.0' (uid=0 pid=690 comm="/nix/store/7m5z8ppk1c5875lfa5fcrlsqggam67mg-xdg-de" label="kernel")
dbus-daemon[712]: [session uid=0 pid=712] Activating service name='org.freedesktop.impl.portal.PermissionStore' requested by ':1.1' (uid=0 pid=726 comm="/nix/store/jyqiimn1ik4rwc05ap3vf378z0za7mmh-xdg-de" label="kernel")
dbus-daemon[712]: [session uid=0 pid=712] Successfully activated service 'org.freedesktop.impl.portal.PermissionStore'
dbus-daemon[712]: [session uid=0 pid=712] Successfully activated service 'org.freedesktop.portal.Documents'
1..5
# Start of db tests
ok 1 /db/version
ok 2 /db/create_doc
path: /tmp/xdp-test-5Z19L0/doc/4532842a/recursive-file
ok 3 /db/recursive_doc
ok 4 /db/create_docs
ok 5 /db/add_named
# End of db tests
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
# GLib-DEBUG: posix_spawn avoided (fd close requested)
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
PASS: xdg-desktop-portal/test-doc-portal.test
Running test: xdg-desktop-portal/test-portals.test
# random seed: R02S4fcd6eed5b1579f99466507b76233f96
outdir: /tmp/xdp-test-21AGM0
# GLib-DEBUG: Launching with posix_spawn
launching test-backend
# GLib-DEBUG: posix_spawn avoided (fd close requested) (child_setup specified)
# xdg-desktop-portal-DEBUG: Name org.freedesktop.impl.portal.Test disappeared

# xdg-desktop-portal-DEBUG: Name org.freedesktop.impl.portal.Test now owned by :1.1

launching xdg-desktop-portal
# GLib-DEBUG: posix_spawn avoided (fd close requested) (child_setup specified)
# xdg-desktop-portal-DEBUG: Name org.freedesktop.portal.Desktop disappeared

dbus-daemon[780]: [session uid=0 pid=780] Activating service name='org.freedesktop.portal.Documents' requested by ':1.2' (uid=0 pid=788 comm="/nix/store/jyqiimn1ik4rwc05ap3vf378z0za7mmh-xdg-de" label="kernel")
dbus-daemon[780]: [session uid=0 pid=780] Activating service name='org.freedesktop.impl.portal.PermissionStore' requested by ':1.3' (uid=0 pid=800 comm="/nix/store/jyqiimn1ik4rwc05ap3vf378z0za7mmh-xdg-de" label="kernel")
dbus-daemon[780]: [session uid=0 pid=780] Successfully activated service 'org.freedesktop.impl.portal.PermissionStore'
dbus-daemon[780]: [session uid=0 pid=780] Successfully activated service 'org.freedesktop.portal.Documents'
Bail out! xdg-desktop-portal-FATAL-ERROR: Failed to launch xdg-desktop-portal

(/nix/store/7m5z8ppk1c5875lfa5fcrlsqggam67mg-xdg-desktop-portal-1.7.2-installedTests/libexec/installed-tests/xdg-desktop-portal/test-portals:779): xdg-desktop-portal-ERROR **: 12:14:29.304: Failed to launch xdg-desktop-portal

** (/nix/store/jyqiimn1ik4rwc05ap3vf378z0za7mmh-xdg-desktop-portal-1.7.2/libexec/xdg-desktop-portal:788): WARNING **: 12:14:29.824: Failed connect to PipeWire: Couldn't connect to PipeWire
cleaning up pid 780
FAIL: xdg-desktop-portal/test-portals.test (Child process killed by signal 5)
Running test: xdg-desktop-portal/testdb.test
# random seed: R02S68a284bd0f6bbc95ad1ce6aec126a6dd
1..3
# Start of db tests
ok 1 /db/open
ok 2 /db/serialize
ok 3 /db/modify
# End of db tests
PASS: xdg-desktop-portal/testdb.test
Running test: xdg-desktop-portal/test-document-fuse.sh.test
1..2
sed: can't read /nix/store/7m5z8ppk1c5875lfa5fcrlsqggam67mg-xdg-desktop-portal-1.7.2-installedTests/libexec/installed-tests/xdg-desktop-portal/session.conf.in: No such file or directory
fusermount: failed to unmount /tmp/xdp-PUwtoV/runtime/doc: No such file or directory
/nix/store/7m5z8ppk1c5875lfa5fcrlsqggam67mg-xdg-desktop-portal-1.7.2-installedTests/libexec/installed-tests/xdg-desktop-portal/test-document-fuse.sh: line 52: /bin/kill: No such file or directory
FAIL: xdg-desktop-portal/test-document-fuse.sh.test (Child process exited with code 127)
Running test: xdg-desktop-portal/test-permission-store.test
# random seed: R02S5e939b5a784d15b685b1b9ef7e4fae1b
outdir: /tmp/xdp-test-YIB6L0
# GLib-DEBUG: Launching with posix_spawn
dbus-daemon[904]: [session uid=0 pid=904] Activating service name='org.freedesktop.impl.portal.PermissionStore' requested by ':1.0' (uid=0 pid=903 comm="/nix/store/7m5z8ppk1c5875lfa5fcrlsqggam67mg-xdg-de" label="kernel")
dbus-daemon[904]: [session uid=0 pid=904] Successfully activated service 'org.freedesktop.impl.portal.PermissionStore'
1..10
# Start of permissions tests
ok 1 /permissions/version
ok 2 /permissions/change
ok 3 /permissions/lookup
ok 4 /permissions/delete1
ok 5 /permissions/delete2
ok 6 /permissions/delete3
ok 7 /permissions/delete4
ok 8 /permissions/create1
ok 9 /permissions/create2
ok 10 /permissions/set-value
# End of permissions tests
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
PASS: xdg-desktop-portal/test-permission-store.test
SUMMARY: total=5; passed=3; skipped=0; failed=2; user=0.1s; system=0.2s; maxrss=7392
FAIL: xdg-desktop-portal/test-portals.test (Child process killed by signal 5)
FAIL: xdg-desktop-portal/test-document-fuse.sh.test (Child process exited with code 127)

error: command `gnome-desktop-testing-runner  -d '/nix/store/7m5z8ppk1c5875lfa5fcrlsqggam67mg-xdg-desktop-portal-1.7.2-installedTests/share' 2>&1` failed (exit code 2)
```

</details>

1. `session.conf.in` is installed to `libexec/installed-tests/xdg-desktop-portal/tests/session.conf.in` instead but 
2. It expects `/bin/kill` exists but we do not have `/bin` in our minimal VMs and only add what is needed to `PATH`.

If I manually patch these two, there are more issues:

```
/nix/store/f0zzvgvbz1gk74yr3mv5rbsvcaiqysaa-xdg-desktop-portal-1.7.2-installedTests/libexec/installed-tests/xdg-desktop-portal/test-document-fuse.sh: line 72: ./xdg-document-portal: No such file or directory
/nix/store/f0zzvgvbz1gk74yr3mv5rbsvcaiqysaa-xdg-desktop-portal-1.7.2-installedTests/libexec/installed-tests/xdg-desktop-portal/test-document-fuse.sh: line 76: python3: command not found
```

But even after fixing these there are some assertions

<details>
<summary>Log</summary>

```
machine # [   27.339550] gnome-desktop-testing-runner[672]: PASS: xdg-desktop-portal/test-doc-portal.test
machine # [   27.356203] gnome-desktop-testing-runner[672]: SUMMARY: total=5; passed=3; skipped=0; failed=2; user=1.5s; system=1.4s; maxrss=23368
machine: output: Running test: xdg-desktop-portal/test-document-fuse.sh.test
1..2
Testing single-threaded
Connecting to portal
Running fuse tests...
Creating some docs
exported /tmp/xdp-eiK1fX/dir1/the-file as 11adbdc6
exported /tmp/xdp-eiK1fX/dir2/the-file as d93a78ec
exported /tmp/xdp-eiK1fX/dir3/the-file as 67d49afc
exported /tmp/xdp-eiK1fX/dir4/the-file as c8d4e010
exported /tmp/xdp-eiK1fX/dir5/the-file as 618d3d15
exported /tmp/xdp-eiK1fX/dir6/the-file as 50508171
exported /tmp/xdp-eiK1fX/dir7/the-file as 291f0a1a
exported /tmp/xdp-eiK1fX/dir8/the-file as add9aa17
exported /tmp/xdp-eiK1fX/dir9/the-file as e0941979
exported /tmp/xdp-eiK1fX/dir10/the-file as 73ea6793
Creating some named docs (existing)
exported (named) /tmp/xdp-eiK1fX/dir11/the-file as 9a526720
exported (named) /tmp/xdp-eiK1fX/dir12/the-file as a1bdd8d1
exported (named) /tmp/xdp-eiK1fX/dir13/the-file as a453a3da
exported (named) /tmp/xdp-eiK1fX/dir14/the-file as f30b3409
exported (named) /tmp/xdp-eiK1fX/dir15/the-file as f37e6a2f
exported (named) /tmp/xdp-eiK1fX/dir16/the-file as 782ee2ad
exported (named) /tmp/xdp-eiK1fX/dir17/the-file as 1fca3aa3
exported (named) /tmp/xdp-eiK1fX/dir18/the-file as ac965be9
exported (named) /tmp/xdp-eiK1fX/dir19/the-file as 50cde51
exported (named) /tmp/xdp-eiK1fX/dir20/the-file as 4ef39a72
Creating some named docs (non-existing)
exported (named) /tmp/xdp-eiK1fX/dir21/the-file as bcb6bc30(missing)
exported (named) /tmp/xdp-eiK1fX/dir22/the-file as 5f0aa569(missing)
exported (named) /tmp/xdp-eiK1fX/dir23/the-file as c8376e5c(missing)
exported (named) /tmp/xdp-eiK1fX/dir24/the-file as 4c120a2c(missing)
exported (named) /tmp/xdp-eiK1fX/dir25/the-file as c35f50b(missing)
exported (named) /tmp/xdp-eiK1fX/dir26/the-file as f58ea714(missing)
exported (named) /tmp/xdp-eiK1fX/dir27/the-file as bbee1673(missing)
exported (named) /tmp/xdp-eiK1fX/dir28/the-file as d2ecb6c8(missing)
exported (named) /tmp/xdp-eiK1fX/dir29/the-file as cac0f029(missing)
exported (named) /tmp/xdp-eiK1fX/dir30/the-file as 9389fb5(missing)
Creating some dir docs
exported (dir) /tmp/xdp-eiK1fX/dir31 as 738c77b9(dir)
exported (dir) /tmp/xdp-eiK1fX/dir32 as 3ce794c(dir)
exported (dir) /tmp/xdp-eiK1fX/dir33 as c6fb691f(dir)
exported (dir) /tmp/xdp-eiK1fX/dir34 as 429e4e5(dir)
exported (dir) /tmp/xdp-eiK1fX/dir35 as b3a30b38(dir)
exported (dir) /tmp/xdp-eiK1fX/dir36 as 31372b9a(dir)
Executing: xdg-desktop-portal/test-document-fuse.sh.test
exported (dir) /tmp/xdp-eiK1fX/dir37 as adbae00c(dir)
exported (dir) /tmp/xdp-eiK1fX/dir38 as 1298ee42(dir)
exported (dir) /tmp/xdp-eiK1fX/dir39 as daf820ec(dir)
exported (dir) /tmp/xdp-eiK1fX/dir40 as ba72993(dir)
Creating some apps
granted acces to org.test.read.App1 and org.test.write.App1 for ['50cde51', '73ea6793', 'abefe771', '62a6ce08', 'e0941979', '93344e1f']
granted acces to org.test.read.App2 and org.test.write.App2 for ['d9395d6f', '73ea6793', 'bd9ac943', '738c77b9', '4c120a2c', '4ef39a72']
granted acces to org.test.read.App3 and org.test.write.App3 for ['f3c1d959', '782ee2ad', 'a1a1159', 'd3e29bfb', 'cac0f029', '3fc34410']
granted acces to org.test.read.App4 and org.test.write.App4 for ['1fca3aa3', 'd93a78ec', 'b3a30b38', '31372b9a', 'c35f50b', '42a48e56']
granted acces to org.test.read.App5 and org.test.write.App5 for ['bd9ac943', '53addac3', 'adbae00c', '33588258', '4c26cb5e', 'a453a3da']
granted acces to org.test.read.App6 and org.test.write.App6 for ['4ab80e15', '1fca3aa3', 'a1a1159', 'ce1819a1', '8695bbeb', '23204b7b']
granted acces to org.test.read.App7 and org.test.write.App7 for ['73ea6793', '618d3d15', '1ee89629', '9389fb5', '1298ee42', '782ee2ad']
granted acces to org.test.read.App8 and org.test.write.App8 for ['3fc34410', '738c77b9', 'cac0f029', '42a48e56', 'c6fb691f', 'c8376e5c']
granted acces to org.test.read.App9 and org.test.write.App9 for ['c35f50b', '4ab80e15', '33a828aa', '370d5366', 'abefe771', '73ea6793']
granted acces to org.test.read.App10 and org.test.write.App10 for ['f3c1d959', 'f58ea714', 'c8376e5c', '93344e1f', 'd9395d6f', '31372b9a']
Checking permissions, pass 1
Traceback (most recent call last):
  File "/nix/store/x7xabx2l0kphwzamh6l2s4mcxlhyf7kw-xdg-desktop-portal-1.7.2-installedTests/libexec/installed-tests/xdg-desktop-portal/test-document-fuse.py", line 938, in <module>
    check_perms()
  File "/nix/store/x7xabx2l0kphwzamh6l2s4mcxlhyf7kw-xdg-desktop-portal-1.7.2-installedTests/libexec/installed-tests/xdg-desktop-portal/test-document-fuse.py", line 769, in check_perms
    check_doc_perms(doc, None)
  File "/nix/store/x7xabx2l0kphwzamh6l2s4mcxlhyf7kw-xdg-desktop-portal-1.7.2-installedTests/libexec/installed-tests/xdg-desktop-portal/test-document-fuse.py", line 760, in check_doc_perms
    check_directory_doc_perms(doc, app_id)
  File "/nix/store/x7xabx2l0kphwzamh6l2s4mcxlhyf7kw-xdg-desktop-portal-1.7.2-installedTests/libexec/installed-tests/xdg-desktop-portal/test-document-fuse.py", line 664, in check_directory_doc_perms
    assertRaises(PermissionError, os.open, dir + "/readonly", os.O_RDWR)
  File "/nix/store/x7xabx2l0kphwzamh6l2s4mcxlhyf7kw-xdg-desktop-portal-1.7.2-installedTests/libexec/installed-tests/xdg-desktop-portal/test-document-fuse.py", line 81, in assertRaises
    raise AssertionError("{0} was not raised".format(exc_type.__name__))
AssertionError: PermissionError was not raised
FAIL: xdg-desktop-portal/test-document-fuse.sh.test (Child process exited with code 1)
Running test: xdg-desktop-portal/test-permission-store.test
# random seed: R02S3d6315c45b0804a03b8a2c9a62d5f9f3
outdir: /tmp/xdp-test-JGG8L0
# GLib-DEBUG: Launching with posix_spawn
dbus-daemon[867]: [session uid=0 pid=867] Activating service name='org.freedesktop.impl.portal.PermissionStore' requested by ':1.0' (uid=0 pid=866 comm="/nix/store/x7xabx2l0kphwzamh6l2s4mcxlhyf7kw-xdg-de" label="kernel")
dbus-daemon[867]: [session uid=0 pid=867] Successfully activated service 'org.freedesktop.impl.portal.PermissionStore'
1..10
# Start of permissions tests
ok 1 /permissions/version
ok 2 /permissions/change
ok 3 /permissions/lookup
ok 4 /permissions/delete1
ok 5 /permissions/delete2
ok 6 /permissions/delete3
ok 7 /permissions/delete4
ok 8 /permissions/create1
ok 9 /permissions/create2
ok 10 /permissions/set-value
# End of permissions tests
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
PASS: xdg-desktop-portal/test-permission-store.test
Running test: xdg-desktop-portal/testdb.test
# random seed: R02Sccff6b54c290ca67de96e364c5dcf516
1..3
# Start of db tests
ok 1 /db/open
ok 2 /db/serialize
ok 3 /db/modify
# End of db tests
PASS: xdg-desktop-portal/testdb.test
Running test: xdg-desktop-portal/test-portals.test
# random seed: R02S7d52ea0053c69453019397833361f1f6
outdir: /tmp/xdp-test-JPRCM0
# GLib-DEBUG: Launching with posix_spawn
launching test-backend
# GLib-DEBUG: posix_spawn avoided (fd close requested) (child_setup specified)
# xdg-desktop-portal-DEBUG: Name org.freedesktop.impl.portal.Test disappeared

# xdg-desktop-portal-DEBUG: Name org.freedesktop.impl.portal.Test now owned by :1.1

launching xdg-desktop-portal
# GLib-DEBUG: posix_spawn avoided (fd close requested) (child_setup specified)
# xdg-desktop-portal-DEBUG: Name org.freedesktop.portal.Desktop disappeared

dbus-daemon[880]: [session uid=0 pid=880] Activating service name='org.freedesktop.portal.Documents' requested by ':1.2' (uid=0 pid=888 comm="/nix/store/y05r5b2pn4q4g67vy7zia96v6xvm33rk-xdg-de" label="kernel")
dbus-daemon[880]: [session uid=0 pid=880] Activating service name='org.freedesktop.impl.portal.PermissionStore' requested by ':1.3' (uid=0 pid=893 comm="/nix/store/y05r5b2pn4q4g67vy7zia96v6xvm33rk-xdg-de" label="kernel")
dbus-daemon[880]: [session uid=0 pid=880] Successfully activated service 'org.freedesktop.impl.portal.PermissionStore'
dbus-daemon[880]: [session uid=0 pid=880] Successfully activated service 'org.freedesktop.portal.Documents'

** (/nix/store/y05r5b2pn4q4g67vy7zia96v6xvm33rk-xdg-desktop-portal-1.7.2/libexec/xdg-desktop-portal:888): WARNING **: 12:48:40.192: Failed connect to PipeWire: Couldn't connect to PipeWire
# xdg-desktop-portal-DEBUG: Name org.freedesktop.portal.Desktop now owned by :1.2

launching xdg-permission-store# GLib-DEBUG: posix_spawn avoided (fd close requested) (child_setup specified)
# xdg-desktop-portal-DEBUG: Name org.freedesktop.impl.portal.PermissionStore now owned by :1.4

1..115
# Start of portal tests
# Start of account tests
ok 1 /portal/account/exists
# libportal-DEBUG: freeing AccountCall
ok 2 /portal/account/basic
# libportal-DEBUG: freeing AccountCall
ok 3 /portal/account/delay
# libportal-DEBUG: freeing AccountCall
ok 4 /portal/account/cancel
# xdg-desktop-portal-DEBUG: cancel call
# libportal-DEBUG: freeing AccountCall
ok 5 /portal/account/close
# libportal-DEBUG: freeing AccountCall

** (/nix/store/y05r5b2pn4q4g67vy7zia96v6xvm33rk-xdg-desktop-portal-1.7.2/libexec/xdg-desktop-portal:888): WARNING **: 12:48:40.868: Backend call failed: Unexpected reason: 'xx' != 'yy'
# libportal-DEBUG: freeing AccountCall
# libportal-DEBUG: freeing AccountCall
ok 6 /portal/account/reason
# libportal-DEBUG: freeing AccountCall
# libportal-DEBUG: freeing AccountCall
# libportal-DEBUG: freeing AccountCall
ok 7 /portal/account/parallel
# End of account tests
# Start of background tests
ok 8 /portal/background/exists
calling background
ok 9 /portal/background/basic1
calling background
ok 10 /portal/background/basic2
calling background
ok 11 /portal/background/commandline
calling background
ok 12 /portal/background/reason
# End of background tests
# Start of camera tests
ok 13 /portal/camera/exists
# libportal-DEBUG: Calling AccessCamera
# xdg-desktop-portal-DEBUG: camera cb: 0
ok 14 /portal/camera/basic
# libportal-DEBUG: Calling AccessCamera
# xdg-desktop-portal-DEBUG: camera cb: 1
ok 15 /portal/camera/delay
# libportal-DEBUG: Calling AccessCamera
# xdg-desktop-portal-DEBUG: cancel call
# libportal-DEBUG: Calling Close
# xdg-desktop-portal-DEBUG: camera cb: 3
ok 16 /portal/camera/close
# libportal-DEBUG: Calling AccessCamera
# xdg-desktop-portal-DEBUG: camera cb: 2
ok 17 /portal/camera/cancel
# libportal-DEBUG: Calling AccessCamera
# xdg-desktop-portal-DEBUG: camera cb: 4
ok 18 /portal/camera/lockdown
# libportal-DEBUG: Calling AccessCamera
# xdg-desktop-portal-DEBUG: camera cb: 0
ok 19 /portal/camera/noaccess1
# libportal-DEBUG: Calling AccessCamera
# xdg-desktop-portal-DEBUG: camera cb: 0
ok 20 /portal/camera/noaccess2
# libportal-DEBUG: Calling AccessCamera
# libportal-DEBUG: Calling AccessCamera
# libportal-DEBUG: Calling AccessCamera
# xdg-desktop-portal-DEBUG: camera cb: 0
# xdg-desktop-portal-DEBUG: camera cb: 0
# xdg-desktop-portal-DEBUG: camera cb: 0
ok 21 /portal/camera/parallel
# End of camera tests
# Start of email tests
ok 22 /portal/email/exists
ok 23 /portal/email/basic
Executing: xdg-desktop-portal/test-portals.test
ok 24 /portal/email/delay
ok 25 /portal/email/cancel
# xdg-desktop-portal-DEBUG: cancel call
# libportal-DEBUG: calling Close
ok 26 /portal/email/close
ok 27 /portal/email/address
ok 28 /portal/email/subject
ok 29 /portal/email/parallel
# End of email tests
# Start of filechooser tests
ok 30 /portal/filechooser/exists
# End of filechooser tests
# Start of gamemode tests
ok 31 /portal/gamemode/exists
# End of gamemode tests
# Start of inhibit tests
ok 32 /portal/inhibit/exists
# xdg-desktop-portal-DEBUG: Got inhibit callback
ok 33 /portal/inhibit/basic
# xdg-desktop-portal-DEBUG: Got inhibit callback
ok 34 /portal/inhibit/delay
# xdg-desktop-portal-DEBUG: cancel call
# libportal-DEBUG: inhibit cancelled, calling Close
# xdg-desktop-portal-DEBUG: Got inhibit callback
ok 35 /portal/inhibit/close
# xdg-desktop-portal-DEBUG: Got inhibit callback
ok 36 /portal/inhibit/cancel
# xdg-desktop-portal-DEBUG: Got inhibit callback
# xdg-desktop-portal-DEBUG: Got inhibit callback
# xdg-desktop-portal-DEBUG: Got inhibit callback
ok 37 /portal/inhibit/parallel
# xdg-desktop-portal-DEBUG: Got inhibit callback
ok 38 /portal/inhibit/permissions
waiting for query-end state
ok 39 /portal/inhibit/monitor
# End of inhibit tests
# Start of location tests
ok 40 /portal/location/exists

** (/nix/store/y05r5b2pn4q4g67vy7zia96v6xvm33rk-xdg-desktop-portal-1.7.2/libexec/xdg-desktop-portal:888): WARNING **: 12:48:45.659: Failed to get GeoClue client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.GeoClue2 was not provided by any .service files
**
xdg-desktop-portal:ERROR:tests/location.c:22:location_cb: 'res' should be TRUE
Bail out! xdg-desktop-portal:ERROR:tests/location.c:22:location_cb: 'res' should be TRUE
cleaning up pid 880

(/nix/store/x7xabx2l0kphwzamh6l2s4mcxlhyf7kw-xdg-desktop-portal-1.7.2-installedTests/libexec/installed-tests/xdg-desktop-portal/test-backends:884): GLib-GObject-CRITICAL **: 12:48:46.202: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
FAIL: xdg-desktop-portal/test-portals.test (Child process killed by signal 6)
Running test: xdg-desktop-portal/test-doc-portal.test
# random seed: R02S51ce6ecec3c4c6b38ae507918e8c8de0
# Successfully set up test FUSE fs on /tmp/xdp-test.HK9EM0
outdir: /tmp/xdp-test-OC6CM0
# GLib-DEBUG: Launching with posix_spawn
dbus-daemon[934]: [session uid=0 pid=934] Activating service name='org.freedesktop.portal.Documents' requested by ':1.0' (uid=0 pid=928 comm="/nix/store/x7xabx2l0kphwzamh6l2s4mcxlhyf7kw-xdg-de" label="kernel")
dbus-daemon[934]: [session uid=0 pid=934] Activating service name='org.freedesktop.impl.portal.PermissionStore' requested by ':1.1' (uid=0 pid=939 comm="/nix/store/y05r5b2pn4q4g67vy7zia96v6xvm33rk-xdg-de" label="kernel")
dbus-daemon[934]: [session uid=0 pid=934] Successfully activated service 'org.freedesktop.impl.portal.PermissionStore'
dbus-daemon[934]: [session uid=0 pid=934] Successfully activated service 'org.freedesktop.portal.Documents'
1..5
# Start of db tests
ok 1 /db/version
ok 2 /db/create_doc
path: /tmp/xdp-test-OC6CM0/doc/927ec684/recursive-file
ok 3 /db/recursive_doc
ok 4 /db/create_docs
ok 5 /db/add_named
# End of db tests
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
# GLib-DEBUG: posix_spawn avoided (fd close requested)
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
# GLib-DEBUG: unsetenv() is not thread-safe and should not be used after threads are created
PASS: xdg-desktop-portal/test-doc-portal.test
SUMMARY: total=5; passed=3; skipped=0; failed=2; user=1.5s; system=1.4s; maxrss=23368
FAIL: xdg-desktop-portal/test-document-fuse.sh.test (Child process exited with code 1)
FAIL: xdg-desktop-portal/test-portals.test (Child process killed by signal 6)
```

</details>

**Comment by GeorgesStavracas** [comment]
Seems like this was fixed with https://github.com/flatpak/xdg-desktop-portal/pull/521. Please reopen if not the case.
