### ISSUE TITLE
Regression in #473: test-portals now fails

### ISSUE THREAD

**Issue by smcv** [flatpak/xdg-desktop-portal#524]
As noted on #521, test-portals now fails when running build-time tests with libportal enabled, which seems to be a regression caused by #473.

To reproduce:
* `./configure --prefix="$HOME/tmp/usr" --enable-pipewire --enable-libportal --enable-installed-tests`
* `make`
* `TEST_IN_CI=1 make check TESTS=test-portals`

With 69205f12 reverted, this passes.

With 5c4e4d22, the test hangs in `test_open_uri_http()` because `xdg-desktop-portal` crashes when `app_exists()` tries to look up `NULL` in a GHashTable:

```#0  g_str_hash (v=0x0) at ../../../glib/ghash.c:2333
#1  0x00007fca72e6eb0b in g_hash_table_lookup_node
    (hash_return=<synthetic pointer>, key=0x0, hash_table=0x557f84507000 = {...}) at ../../../glib/ghash.c:1511
#2  g_hash_table_lookup (hash_table=0x557f84507000 = {...}, key=key@entry=0x0) at ../../../glib/ghash.c:1511
#3  0x00007fca730828ca in desktop_file_dir_unindexed_get_app (desktop_id=0x0, dir=<optimized out>)
    at ../../../gio/gdesktopappinfo.c:1428
#4  desktop_file_dir_get_app (desktop_id=0x0, dir=<optimized out>) at ../../../gio/gdesktopappinfo.c:1428
#5  g_desktop_app_info_new (desktop_id=0x0) at ../../../gio/gdesktopappinfo.c:1983
#6  0x0000557f8282e97f in app_exists (app_id=<optimized out>) at src/open-uri.c:676
#7  handle_open_in_thread_func
    (task=<optimized out>, source_object=<optimized out>, task_data=0x557f8445dad0, cancellable=<optimized out>)
    at src/open-uri.c:676
#8  0x00007fca7306afae in g_task_thread_pool_thread (thread_data=0x557f84447ef0, pool_data=<optimized out>)
    at ../../../gio/gtask.c:1417
#9  0x00007fca72eab694 in g_thread_pool_thread_proxy (data=<optimized out>) at ../../../glib/gthreadpool.c:354
#10 0x00007fca72eaadad in g_thread_proxy (data=0x557f844ddcc0) at ../../../glib/gthread.c:819
#11 0x00007fca72e16ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#12 0x00007fca72d44eaf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

After fixing that, the test still fails in `test_open_uri_http2()`, because that test configures permissions as though the mock web browser `furrfix.desktop` had been the http URI handler on 3 out of 3 recent occasions and asserts that we are not asked to choose a http URI handler, but in fact we get asked.

I'm working on a fix for this.

cc @hadess, @mcatanzaro

**Comment by smcv** [comment]
#525 fixes this, and hence the CI.

#521 would also be good to have for CI coverage.
